name: Terraform Branch Protection

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop
    paths:
      - 'terraform/**'

# Cancela execuções antigas no GitHub se um novo commit chegar
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - run: terraform init

      - run: terraform apply -auto-approve
        env:
          TF_VAR_github_token: ${{ secrets.TF_GITHUB_PAT }}